# -*- coding: utf-8 -*-
"""Brownian Motion Paths - Generalized

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQfbPv4niR4LDr4Ccpv3TZzcy50vRu-E
"""

!pip install fbm -q
import numpy as np
import matplotlib.pyplot as plt
import fbm
import warnings
warnings.filterwarnings('ignore')
print("Generating theoretical plots for paper figures...")

# --- Common Parameters (from PDF, Section 2.1) ---
T = 10.0
DT = 0.01
N_STEPS = int(T / DT)
t_vec = np.linspace(0, T, N_STEPS + 1)
np.random.seed(42)

# --- 1. Figure 1: Standard Brownian Motion (BM) ---
# PDF (Sec 2.1): "interval [0, 10] with a step of 0.01"
print("Generating Figure 1: Standard Brownian Motion...")
b_path = np.concatenate(([0], np.cumsum(np.random.normal(0, 1, N_STEPS) * np.sqrt(DT))))

plt.figure(figsize=(10, 6))
plt.plot(t_vec, b_path)
plt.title('Figure 1: Sample Trajectory of Standard Brownian Motion (H=0.5)')
plt.xlabel('Time (t)')
plt.ylabel('B(t)')
plt.grid(True)
plt.savefig('figure_1_bm.png')
print("Saved figure_1_bm.png")

# --- 2. Figure 2: Geometric Brownian Motion (GBM) ---
# PDF (Sec 2.2): "mu=0.7 and sigma=0.3"
print("Generating Figure 2: Geometric Brownian Motion...")
MU_GBM_T = 0.7
SIGMA_GBM_T = 0.3
S0_T = 100

gbm_path = S0_T * np.exp((MU_GBM_T - SIGMA_GBM_T**2 / 2) * t_vec + SIGMA_GBM_T * b_path)
plt.figure(figsize=(10, 6))
plt.plot(t_vec, gbm_path)
plt.title(f'Figure 1: Sample Trajectory of Geometric Brownian Motion (μ={MU_GBM_T}, σ={SIGMA_GBM_T})')
plt.xlabel('Time (t)')
plt.ylabel('S(t)')
plt.grid(True)
plt.savefig('figure_2_gbm.png')
print("Saved figure_2_gbm.png")

# --- 3. Figure 3: Fractional Brownian Motion (fBM) ---
# PDF (Sec 2.3): "sigma=0.3 and H=0.4"
print("Generating Figure 3: Fractional Brownian Motion...")
SIGMA_FBM_T = 0.3
H_FBM_T = 0.4

fbm_path_raw = fbm.FBM(n=N_STEPS, hurst=H_FBM_T, length=T, method='daviesharte').fbm()
fbm_path = SIGMA_FBM_T * fbm_path_raw

plt.figure(figsize=(10, 6))
plt.plot(t_vec, fbm_path)
plt.title(f'Figure 2: Sample Trajectory of Fractional Brownian Motion (σ={SIGMA_FBM_T}, H={H_FBM_T})')
plt.xlabel('Time (t)')
plt.ylabel('B^H(t)')
plt.grid(True)
plt.savefig('figure_3_fbm.png')
print("Saved figure_3_fbm.png")

# --- 4. Figure 4: Geometric Fractional Brownian Motion (GfBM) ---
# PDF (Sec 2.4): "mu=0.7, sigma=0.8, and H=0.4"
print("Generating Figure 4: Geometric Fractional Brownian Motion...")
MU_GFBM_T = 0.7
SIGMA_GFBM_T = 0.8
H_GFBM_T = 0.4

fbm_path_raw_2 = fbm.FBM(n=N_STEPS, hurst=H_GFBM_T, length=T, method='daviesharte').fbm()
gfbm_path = S0_T * np.exp((MU_GFBM_T - SIGMA_GFBM_T**2 / 2) * t_vec + SIGMA_GFBM_T * fbm_path_raw_2)

plt.figure(figsize=(10, 6))
plt.plot(t_vec, gfbm_path)
plt.title(f'Figure 3: Sample Trajectory of Geometric Fractional Brownian Motion (μ={MU_GFBM_T}, σ={SIGMA_GFBM_T}, H={H_GFBM_T})')
plt.xlabel('Time (t)')
plt.ylabel('S(t)')
plt.grid(True)
plt.savefig('figure_4_gfbm.png')
print("Saved figure_4_gfbm.png")

print("\nAll theoretical plots generated and saved as PNG files.")
plt.show()

"""# Task
Extract and display the parameters for each figure: Figure 1 (Standard Brownian Motion) with H=0.5, Figure 2 (Geometric Brownian Motion) with μ=0.7 and σ=0.3, Figure 3 (Fractional Brownian Motion) with σ=0.3 and H=0.4, and Figure 4 (Geometric Fractional Brownian Motion) with μ=0.7, σ=0.8, and H=0.4.

## Extract and Display Parameters

### Subtask:
Identify and display the μ (mu), σ (sigma), and Hurst (H) parameters for each of the four figures.

## Summary:

### Data Analysis Key Findings

*   **Figure 1 (Standard Brownian Motion)**: The Hurst parameter (H) was identified as 0.5.
*   **Figure 2 (Geometric Brownian Motion)**: The drift parameter (\$\mu\$) was identified as 0.7, and the volatility parameter (\$\sigma\$) was identified as 0.3.
*   **Figure 3 (Fractional Brownian Motion)**: The volatility parameter (\$\sigma\$) was identified as 0.3, and the Hurst parameter (H) was identified as 0.4.
*   **Figure 4 (Geometric Fractional Brownian Motion)**: The drift parameter (\$\mu\$) was identified as 0.7, the volatility parameter (\$\sigma\$) was identified as 0.8, and the Hurst parameter (H) was identified as 0.4.

### Insights or Next Steps

*   The specified parameters for each model are now clearly defined, providing the necessary input for subsequent simulation or theoretical analysis of these stochastic processes.
*   The next step will involve utilizing these parameters to generate and visualize the respective Brownian motion paths.
"""